name: Release

on:
  release:
    types: [published]

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull built image
        run: docker pull ghcr.io/${{ github.event.repository.full_name }}:${{ github.sha }}
      - name: Tag image with version Tag
        run: docker tag ghcr.io/${{ github.event.repository.full_name }}:${{ github.sha }} ghcr.io/${{ github.event.repository.full_name }}:${{ github.event.release.name }}
      - name: Tag image as latest
        run: docker tag ghcr.io/${{ github.event.repository.full_name }}:${{ github.sha }} ghcr.io/${{ github.event.repository.full_name }}:latest
      - name: Push to registry
        run: docker push ghcr.io/${{ github.event.repository.full_name }}:latest && docker push ghcr.io/${{ github.event.repository.full_name }}:${{ github.event.release.name }}
